language: csharp
solution: src/Sharpility.sln
before_install:
  - sudo apt-get update
  - sudo apt-get install -qq doxygen
install:
  - nuget restore src/Sharpility.sln
  - nuget install NUnit.Runners -Version 2.6.4 -OutputDirectory testrunner
script:
  - xbuild /p:Configuration=Release src/Sharpility.sln
  - mono ./testrunner/NUnit.Runners.2.6.4/tools/nunit-console.exe ./src/Sharpility.Tests/bin/Release/Sharpility.Tests.dll
env:
  global:
    secure: TvoO+cJmRLtCc4oAgv/4bzO0IU5Iwh+Fsha9uvWEH8jaLUFPmWXi5ifRvn7AryWy6zRV+FYeFMe1OvEYJhmcuJ2DbdRCMTL3+KRlS8xPRGmO13b/ulcBv30Ws0RTPKdK+buFbdhkF2YYwHMuSFlTvMOf5WtvPBv+rg3oiF/JV0g2bR+H1HL8EZ30SfNrvtiQkjnrrJrDjkDCdqQb/J4VVp0XZt+yEr1JyiHpVDtuHS+MWkzdmWCs9YVM5LuUCaMwFs53sdvzRWs5D+U63OJx1xiIo0TJnaMHwsVIAtXxamFMrsYwjKsPdN4rtD2M99M6H/22rb8d8kl+Scq24rdbZoo+5O6O0bQMd2sYPlWadElBIzLrzZ6toEqLzJWjqrCSalL8uk/cHmqrzEDgbpa4fEFC/F+Z15y9ioE8otUn+7s++qp1a2zC/4rDoiUVgPQwgzrWL/YqQEThXQwJHEuwNr4BzlGxAZIY9ELlFEuOfm5LTgtVzRrDBcxF1Qvpw5OmF6z3j1xDHl5hVtIf1tpRZOzEbLsh3++n/eoD9FV97oOwU/GRUqGBuKjW5EKxPtELSAfdof6gwICUkI0PghSnh83DY2SiCVjxtVf453zqL2REPPDolzm13ObihHkLofiJl0dTWd/sosYqMWFIFgPL4sHWoY4BJDHv/b9jU465BiE=
after_success:
  - set -o errexit -o nounset
  - rev=$(git rev-parse --short HEAD)
  - doxygen doxygen.config
