language: csharp
solution: src/Sharpility.sln
install:
  - nuget restore src/Sharpility.sln
  - nuget install NUnit.Runners -Version 2.6.4 -OutputDirectory testrunner
script:
  - xbuild /p:Configuration=Release src/Sharpility.sln
  - mono ./testrunner/NUnit.Runners.2.6.4/tools/nunit-console.exe ./src/Sharpility.Tests/bin/Release/Sharpility.Tests.dll