var namespace_sharpility_1_1_collections =
[
    [ "AbstractCompositeDictionary-g", "class_sharpility_1_1_collections_1_1_abstract_composite_dictionary-g.html", null ],
    [ "AbstractMultiDictionary-g", "class_sharpility_1_1_collections_1_1_abstract_multi_dictionary-g.html", null ],
    [ "AbstractSortedMappedQueue-g", "class_sharpility_1_1_collections_1_1_abstract_sorted_mapped_queue-g.html", null ],
    [ "ArrayListMultiDictionary-g", "class_sharpility_1_1_collections_1_1_array_list_multi_dictionary-g.html", null ],
    [ "ArrayListSortedMappedQueue-g", "class_sharpility_1_1_collections_1_1_array_list_sorted_mapped_queue-g.html", null ],
    [ "ComparableDictionary-g", "class_sharpility_1_1_collections_1_1_comparable_dictionary-g.html", null ],
    [ "ComparableList-g", "class_sharpility_1_1_collections_1_1_comparable_list-g.html", null ],
    [ "ComparableSet-g", "class_sharpility_1_1_collections_1_1_comparable_set-g.html", null ],
    [ "CompositeDictionary-g", "interface_sharpility_1_1_collections_1_1_composite_dictionary-g.html", null ],
    [ "CompositeKey-g", "struct_sharpility_1_1_collections_1_1_composite_key-g.html", null ],
    [ "DefaultQueue-g", "class_sharpility_1_1_collections_1_1_default_queue-g.html", null ],
    [ "HashCompositeDictionary-g", "class_sharpility_1_1_collections_1_1_hash_composite_dictionary-g.html", null ],
    [ "HashSetMultiDictionary-g", "class_sharpility_1_1_collections_1_1_hash_set_multi_dictionary-g.html", null ],
    [ "ImmutableCompositeDictionary-g", "class_sharpility_1_1_collections_1_1_immutable_composite_dictionary-g.html", null ],
    [ "ImmutableListMultiDictionary-g", "class_sharpility_1_1_collections_1_1_immutable_list_multi_dictionary-g.html", null ],
    [ "ImmutableMultiDictionary-g", "class_sharpility_1_1_collections_1_1_immutable_multi_dictionary-g.html", null ],
    [ "ImmutableSetMultiDictionary-g", "class_sharpility_1_1_collections_1_1_immutable_set_multi_dictionary-g.html", null ],
    [ "IQueue-g", "interface_sharpility_1_1_collections_1_1_i_queue-g.html", null ],
    [ "LinkedListMultiDictionary-g", "class_sharpility_1_1_collections_1_1_linked_list_multi_dictionary-g.html", null ],
    [ "LinkedQueue-g", "class_sharpility_1_1_collections_1_1_linked_queue-g.html", null ],
    [ "MappedQueue-g", "interface_sharpility_1_1_collections_1_1_mapped_queue-g.html", null ],
    [ "MultiDictionary-g", "interface_sharpility_1_1_collections_1_1_multi_dictionary-g.html", null ],
    [ "OrderedHashImmutableDictionary-g", "class_sharpility_1_1_collections_1_1_ordered_hash_immutable_dictionary-g.html", null ],
    [ "OrderedImmutableDictionary-g", "interface_sharpility_1_1_collections_1_1_ordered_immutable_dictionary-g.html", null ],
    [ "SortedMappedQueue-g", "interface_sharpility_1_1_collections_1_1_sorted_mapped_queue-g.html", null ],
    [ "SortedSetMappedQueue-g", "class_sharpility_1_1_collections_1_1_sorted_set_mapped_queue-g.html", null ]
];